language: node_js
node_js:
  - "node"
  - "lts/*"
after_success:
  - bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"
  - nyc report --reporter=text-lcov | coveralls
